Full-Batch Gradient Descent — Summary

Suppose our network has:

18 weights
4 biases
22 total parameters
100 training samples
What happens in one epoch?
Entire X_train
      ↓
Forward Pass
      ↓
100 predictions
      ↓
Calculate loss for each sample
      ↓
Average the 100 losses
      ↓
One overall loss
      ↓
loss.backward()
      ↓
22 individual gradients
      ↓
Update all 22 parameters
Important distinction

The same overall loss is used as the objective for every parameter.

But each parameter gets its own gradient:

∂w
1
	​

∂L
	​

,
∂w
2
	​

∂L
	​

,...,
∂b
4
	​

∂L
	​


Therefore, each parameter gets a different update.

                 SAME OVERALL LOSS
                        ↓
          ┌─────────────┼─────────────┐
          ↓             ↓             ↓
         w₁            w₂            b₁
          ↓             ↓             ↓
      gradient       gradient       gradient
          ↓             ↓             ↓
      update w₁     update w₂     update b₁
Why average the loss?

The average loss gives us one measure of how well the entire model is performing across the training dataset.

The gradients then tell us:

How does changing each individual parameter affect that overall loss?

So:

Same objective→different gradient per parameter→different update per parameter
	​

What is your current approach called?

Full-Batch Gradient Descent

Entire training dataset → one forward/backward pass
One overall loss
All parameters updated once
Therefore, 1 epoch = 1 parameter-update step

X_test and y_test are not used for training; they're used afterward to evaluate the trained model.

In [ ]:
# so we should use mini batch gradient descent(more practical) or SGD

In [1]:
from sklearn.datasets import make_classification
import torch

In [2]:
# Step 1: Create a synthetic classification dataset using sklearn
X, y = make_classification(
    n_samples=10,       # Number of samples
    n_features=2,       # Number of features
    n_informative=2,    # Number of informative features
    n_redundant=0,      # Number of redundant features
    n_classes=2,        # Number of classes
    random_state=42     # For reproducibility
)

In [3]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [4]:
X.shape

(10, 2)

In [5]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [6]:
y.shape

(10,)

In [7]:
# Convert this data to pytorch tensors
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [8]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [9]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [10]:
from torch.utils.data import Dataset, DataLoader

In [11]:
class CustomDataset(Dataset):

  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [12]:
dataset = CustomDataset(X, y)

In [13]:
dataset.features

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [14]:
len(dataset)

10

In [15]:
dataset[2]

(tensor([-2.8954,  1.9769]), tensor(0))

In [16]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=False)

In [17]:
for batch_features, batch_labels in dataloader:

  print(batch_features)
  print(batch_labels)
  print("-"*50)

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]])
tensor([1, 0])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [-0.7206, -0.9606]])
tensor([0, 0])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]])
tensor([0, 1])
--------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [ 1.7774,  1.5116]])
tensor([1, 1])
--------------------------------------------------
tensor([[ 1.8997,  0.8344],
        [-0.5872, -1.9717]])
tensor([1, 0])
--------------------------------------------------
