<a href="https://colab.research.google.com/github/shivakr07/Machine-Learning/blob/main/NN%2BOptim_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):
    super().__init__()

    # since we have one layer so we call it linear
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [2]:
# Dataset
features = torch.rand(10, 5)
model = Model(features.shape[1])

# to call forward need not to do : model.forward()
# as it is already overwritten : magic function
model(features)

tensor([[0.6211],
        [0.6707],
        [0.7207],
        [0.6109],
        [0.6603],
        [0.6057],
        [0.6713],
        [0.7014],
        [0.6914],
        [0.5632]], grad_fn=<SigmoidBackward0>)

In [7]:
# to check the weights and bias
print(model.linear.weight)
print(model.linear.bias)

Parameter containing:
tensor([[ 0.4250, -0.3438,  0.3288, -0.3785,  0.3562]], requires_grad=True)
Parameter containing:
tensor([0.4270], requires_grad=True)


In [ ]:
# to visualize
